k=0
#CSR

#COO

NAME[$k]="SYM COO ASYNC_NAIVE"
k=$k+1
NAME[$k]="SYM COO ASYNC_COMPRESS"
k=$k+1
NAME[$k]="SYM COO ASYNC_A_HALVE"
k=$k+1
NAME[$k]="SYM COO ASYNC_A_SPLIT"
k=$k+1

NAME[$k]="SYM COO STOPT_NAIVE"
k=$k+1
NAME[$k]="SYM COO STOPT_COMPRESS"
k=$k+1
NAME[$k]="SYM COO STOPT_A_HALVE"
k=$k+1
NAME[$k]="SYM COO STOPT_A_SPLIT"
k=$k+1

NAME[$k]="SYM COO EARLY_NAIVE"
k=$k+1
NAME[$k]="SYM COO EARLY_COMPRESS"
k=$k+1
NAME[$k]="SYM COO EARLY_A_HALVE"
k=$k+1
NAME[$k]="SYM COO EARLY_A_SPLIT"
k=$k+1

NAME[$k]="SYM COO RAND_NAIVE" 
k=$k+1
NAME[$k]="SYM COO RAND_SPLIT_2" 
k=$k+1


NAME[$k]="SYM COO REMCAS_NAIVE_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_COMPRESS_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_A_HALVE_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_A_SPLIT_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_NAIVE_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_COMPRESS_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_A_HALVE_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_A_SPLIT_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMCAS_NAIVE_SPLICE_CAS"
k=$k+1
NAME[$k]="SYM COO REMCAS_A_HALVE_SPLICE_CAS"
k=$k+1
NAME[$k]="SYM COO REMCAS_A_SPLIT_SPLICE_CAS"
k=$k+1

NAME[$k]="SYM COO REMLOCK_NAIVE_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_COMPRESS_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_A_HALVE_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_A_SPLIT_HALVE_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_NAIVE_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_COMPRESS_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_A_HALVE_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_A_SPLIT_SPLIT_ONE"
k=$k+1
NAME[$k]="SYM COO REMLOCK_NAIVE_SPLICE_CAS"
k=$k+1
NAME[$k]="SYM COO REMLOCK_A_HALVE_SPLICE_CAS"
k=$k+1
NAME[$k]="SYM COO REMLOCK_A_SPLIT_SPLICE_CAS"
k=$k+1

NAME[$k]="SYM COO SIM_C_R_S_A"
k=$k+1
NAME[$k]="SYM COO SIM_P_R_S_A"
k=$k+1
NAME[$k]="SYM COO SIM_P_R_S"
k=$k+1

NAME[$k]="SYM COO SIM_C_R_SS_A"
k=$k+1
NAME[$k]="SYM COO SIM_P_R_SS_A"
k=$k+1
NAME[$k]="SYM COO SIM_P_R_SS"
k=$k+1

NAME[$k]="SYM COO SVA"
k=$k+1

DIR="file_location"
EXEC="file_name"

######for each file, you can elaborate as follows.

#for ((j=0;j<$k;j++))
#do
#echo -n ${NAME[$j]}
#echo -n ","
#${DIR}/${EXEC} mtx_file_name ${NAME[$j]}
#done



